const env = process.env.NODE_ENV || 'development';
const serverIP = 'localhost';
const serverPort = 5000;
export default {
  CUSTOMER: 'customer',
  CREATOR: 'creator',
  CONTEST_STATUS_ACTIVE: 'active',
  CONTEST_STATUS_FINISHED: 'finished',
  CONTEST_STATUS_PENDING: 'pending',
  NAME_CONTEST: 'name',
  LOGO_CONTEST: 'logo',
  TAGLINE_CONTEST: 'tagline',
  OFFER_STATUS_REJECTED: 'rejected',
  OFFER_STATUS_WON: 'won',
  OFFER_STATUS_PENDING: 'pending',
  STATIC_IMAGES_PATH: '/staticImages/',
  ANONYM_IMAGE_PATH: '/staticImages/anonym.png',
  BASE_URL: `http://${serverIP}:${serverPort}/`,
  ACCESS_TOKEN: 'accessToken',
  publicURL:
    env === 'production'
      ? `http://${serverIP}:80/images/`
      : `http://${serverIP}:${serverPort}/public/images/`,
  NORMAL_PREVIEW_CHAT_MODE: 'NORMAL_PREVIEW_CHAT_MODE',
  FAVORITE_PREVIEW_CHAT_MODE: 'FAVORITE_PREVIEW_CHAT_MODE',
  BLOCKED_PREVIEW_CHAT_MODE: 'BLOCKED_PREVIEW_CHAT_MODE',
  CATALOG_PREVIEW_CHAT_MODE: 'CATALOG_PREVIEW_CHAT_MODE',
  CHANGE_BLOCK_STATUS: 'CHANGE_BLOCK_STATUS',
  ADD_CHAT_TO_OLD_CATALOG: 'ADD_CHAT_TO_OLD_CATALOG',
  CREATE_NEW_CATALOG_AND_ADD_CHAT: 'CREATE_NEW_CATALOG_AND_ADD_CHAT',
  USER_INFO_MODE: 'USER_INFO_MODE',
  CASHOUT_MODE: 'CASHOUT_MODE',
  HEADER_ANIMATION_TEXT: [
    'a Company',
    'a Brand',
    'a Website',
    'a Service',
    'a Book',
    'a Business',
    'an App',
    'a Product',
    'a Startup',
  ],
  FooterItems: [
    {
      title: 'SQUADHELP',
      items: ['About', 'Contact', 'How It Works?', 'Testimonials', 'Our Work'],
    },
    {
      title: 'RESOURCES',
      items: [
        'How It Works',
        'Become a Creative',
        'Business Name Generator',
        'Discussion Forum',
        'Blog',
        'Download eBook',
        'Pricing',
        'Help & FAQs',
      ],
    },
    {
      title: 'OUR SERVICES',
      items: [
        'Naming',
        'Logo Design',
        'Taglines',
        'Premium Names For Sale',
        'Creative Owned Names For Sale',
        'Audience Testing',
        'Trademark Research & Filling',
        'Managed Agency Service',
      ],
    },
    {
      title: 'LEGAL',
      items: ['Terms of Service', 'Privacy Policy', 'Cookie Policy'],
    },
  ],
  HEADER_LI_ITEM: {
    NAME_IDEAS: [
      'Beauty',
      'Consulting',
      'E-Commerce',
      'Fashion & Clothing',
      'Finance',
      'Real Estate',
      'Tech',
      'More Categories',
    ],
    OUR_WORK: ['Names', 'Taglines', 'Logos', 'Testimonials'],
    CONTESTS: [
      'How It Works',
      ,
      'Pricing',
      'Agence Services',
      'Active Contests',
      'Winners',
      'Leaderboard',
      'Become A Creative',
    ],
    NAMES_FOR_SALE: [
      'Popular Names',
      'Short Names',
      'Intriguing Names',
      'Names By Categories',
      'Visual Name Search',
      'Sell Your Domains',
    ],
    BLOG: [
      'Ultimate Naming Guard',
      'Poetic Devices In Bussines Naming',
      'Crowed Bar Theory',
      'All Articles',
    ],
    LINK: 'http://www.google.com',
  },
  SELECT_PRICING: [
    'Name',
    'Logo',
    'Tegline',
    'Name and Logo',
    'Name and Tagline',
    'Name and Tagline, Logo',
    'Name,Logo and Bussines',
    'Logo and Bussines card',
    'Logo and Tagline',
    'Bussines card',
    'Stationery',
    'Product Feedback and Research',
  ],
  PRICING_BRONZE: {
    MAIN: ['Bronze', 'Branding on a budget', 299],
    LI_EL: [
      'Prize to Winner - $135 (Included)',
      'Validation Services & Upgrades ($39 value)',
      ['Matching .com URL'],
      'Expected 300+ Entries',
    ],
  },
  PRICING_GOLD: {
    MAIN: ['Gold', 'Increase participation and basic brand validation', 449],
    LI_EL: [
      'Prize to Winner - $200 (Included)',
      'Validation Services & Upgrades ($305 value)',
      [
        'Matching .com URL',
        ' Instant Trademark Check (One Database)',
        'NDA and More Privacy',
        'Project Promotion (Basic)',
        ' Comprehensive Trademark Research',
      ],
      'Expected 600+ Entries',
      'Partial Refund Option',
    ],
  },
  PRICING_PLATINUM: {
    MAIN: [
      'Platinum',
      'Work with top-level creatives, plus agency-style brand validation',
      749,
    ],
    LI_EL: [
      'Prize to Winner - $300 (Included)',
      'Validation Services & Upgrades ($979 value)',
      ['Audience Testing (Up to 6 Names) View Sample Report',
      'Comprehensive Trademark Research (3 Names)',
      'Tier A Creatives',
      'Matching .com URL',
      ' Instant Trademark Check (4 Databases)',
      'NDA and More Privacy',
      'Enhanced Project Promotion',
      ' Team Collaboration Tools'],
      'Expected 1000+ Entries',
      'Partial Refund Option',
    ],
  },
  PRICING_MANAGED: {
    MAIN: [
      'Managed',
      'A full agency experience without the agency price tag',
      1499,
    ],
    LI_EL: [
      'Receive optimum results from your Platinum Contest by launching a Managed Contest Package and working one-on-one with an experienced Squadhelp Branding Consultant.With significantly more validation services, professional brief creation, and daily management of your contest by your Branding Expert, you`ll receive an enhanced branding experience to closeout your branding project.Learn More about Managed Contest Service',
    ],
  },
};
